name: lstm stock model
permissions:
  id-token: write
  contents: write

on:
 - push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v3
      - name: model prediction
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN}}

        run: |
          pip install -r requirements.txt
          python stock_prediction_model.py
